# Generated by Django 5.1.2 on 2024-11-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='codigo',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
