# Generated by Django 5.1.2 on 2024-11-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos_app', '0002_alter_instrumento_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
