# Generated by Django 5.1.2 on 2024-11-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.IntegerField(primary_key=True, serialize=False)),
                ('horarios', models.CharField(max_length=100)),
                ('pisos', models.CharField(max_length=100)),
                ('instrumentos', models.CharField(max_length=100)),
                ('oficinas', models.CharField(max_length=100)),
                ('empleados', models.CharField(max_length=100)),
                ('materiales', models.CharField(max_length=100)),
            ],
        ),
    ]
