# Generated by Django 5.1 on 2024-11-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('tipo_instrumento', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre', models.CharField(max_length=100)),
                ('tamaño', models.CharField(max_length=100)),
            ],
        ),
    ]
