# Generated by Django 5.1.2 on 2024-11-29 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0002_empleado_delete_instrumento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='color',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='marca',
        ),
    ]
