# Generated by Django 5.1.2 on 2024-11-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0004_alter_empleado_id_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='id_empleado',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
